# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5dbf8efab98a5dc56a2db18a8624b2d1e1f81bf95d3d384282d654a935e51034ebb102f3e4493bcd1a37bc8f949be8c7b1352c245c3423a0ff4b5fd1ecbe66b

test:
  secret_key_base: 3c1e16a7dc7007ae9bd3072371472669be5cc6e7b854fe22df7e42a22b94c811a29529773d7d2fe7bdda339747d5860aa740820acb26e338b68e4ef5f94f4a5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
